services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./Database/data:/var/lib/mysql
      - ./Database/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  golang-app:
    build: 
      context: ./Webservice
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_PORT=3306
    networks:
      - app-network
  # vue-app:
  #   build: 
  #     context: ./Frontend/air-controller-dashboard
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     golang-app:
  #       condition: service_started
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge